//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace IngredientCatalog
{
    public partial class Recipe
    {
        public Recipe()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int RecipeId { get; set; }
        public string Name { get; set; }
        public string Ingredients { get; set; }
        public string Instructions { get; set; }
        public string PictureURL { get; set; }
        public string Contributer { get; set; }
        public string Category { get; set; }
        public string ServingSize { get; set; }
        public string RecipeOrigin { get; set; }
    
        public virtual ICollection<Note> Notes { get; set; }
    }
    
}
